name: Build for the web with Emscripten

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: emscripten/emsdk:latest
            volumes:
                - ${{ github.workspace }}:/workdir
        steps:
            - name: Run build script
              run: sh /workdir/build_web_emsdk_container.sh