name: Build for the web with Emscripten

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: emscripten/emsdk:latest
            # volumes:
            #     - ${{ github.workspace }}:/workdir
        steps:
            - uses: actions/checkout@v4

            - name: Run build script
              run: ls